### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by spodude** [formtools/website#11]
http://modules.formtools.org/mass_edit/

404

**Comment by benkeen** [comment]
Ooh thanks. That module has been deprecated, so there's no corresponding link. I'll add a page to explain it though. :)

**Comment by benkeen** [comment]
Actually, the module is so dated now I'm just going to leave it be. Closing.

**Comment by nadzws** [comment]
so why do yo still have it in the extensions ?
the documents are obviously missing to 
https://docs.formtools.org/modules/mass_edit
and also for these 
https://docs.formtools.org/modules/media_gallery
https://docs.formtools.org/modules/ft1_data_import

**Comment by benkeen** [comment]
Ah thanks @almarzoqui - yeah I'll remove them from the extensions page. That page is autogenerated, so I'll need add a flag to the DB for deprecated modules.

**Comment by cjohnsonuk** [comment]
Mass edit still showing in modules list, still giving an oops page, Download still working but no code in the zip

**Comment by benkeen** [comment]
Bah! Apologies. Let me look at that right now. I just removed them from the DB so they won't get listed any more. Thanks @cjohnsonuk.
