### ISSUE TITLE
missing doc page

### ISSUE THREAD

**Issue by meanderman** [formtools/website#13]
Missing page:
docs.formtools.org/encrypt.php

**Comment by benkeen** [comment]
Ooh, thanks @meanderman. I'm just out of town for a few days, but I'll patch this up when I get back. 

Sorry for the inconvenience!

**Comment by benkeen** [comment]
Gah, sorry for not getting to this sooner. Been short on time these last few days. I haven't forgotten & it's on my list. :)

**Comment by benkeen** [comment]
All fixed. 

The feature is now found here: https://formtools.org/password_reset.php

The tutorial has been put online here: https://docs.formtools.org/tutorials/resetting_admin_password/
