### ISSUE TITLE
Broken link in Paypal tutorial

### ISSUE THREAD

**Issue by mrheffner** [formtools/website#14]
https://docs.formtools.org/tutorials/paypal/?page=index

**Comment by benkeen** [comment]
Thanks @mrheffner! I've a couple of fixes I need to make this weekend. I'll include this too.

**Comment by benkeen** [comment]
EDIT: hmm, so it looks like the PayPal tutorial wasn't ported over, so the 404 is actually correct. Do you recall what linked to this page?

**Comment by mrheffner** [comment]
Sorry.  I am a brand new formtools user.  I was just doing research for my project.  Wish I could help more.

**Comment by benkeen** [comment]
No worries! I'm working on adding the tutorial back now. Sorry for the fuss! :)

**Comment by mrheffner** [comment]
Looking forward to seeing that.  I think I may want to use that feature.

**Comment by jlkane** [comment]
10 months later and all the links from this page (Setting up a PayPal-Enabled Form, https://docs.formtools.org/tutorials/paypal/step1/) are STILL broken!  One of the truly deeply exceptional things about Form Tools has always been the quality of the documentation.  I'll be introducing a new client to Form Tools next week, and one of the things that's critical to her is this functionality.  I'd LOVE to be able to walk her through this tutorial!  Any chance?

**Comment by benkeen** [comment]
Sorry @jlkane! Problem with FT is that the buck stops entirely with me, and I have to wear an awful lot of hats. I should have time this weekend to look at this.

**Comment by jlkane** [comment]
Benjamin Keen wrote:
> 
> I'll take a look at this this weekend.

Thanks for trying, Ben.  It wouldn't seem as if I'm the only one who would be interested in that tutorial!

> Problem with FT is that the buck stops entirely with me, and I have to wear an awful lot of hats.

I can only imagine.  I remain in awe of all you do for the community with FT, and in *special* awe of your ability to put together exceptional documentation!

All the best,

Jim
---
Jim Kane
Simply Effective Web Sites
http://simply-effective.com
(585) 442-7974

**Comment by benkeen** [comment]
Hi Jim, all fixed! It's back online here: https://docs.formtools.org/tutorials/paypal/

Again, sorry it took so long to get back on line. Ultimately I'd like this module to be irrelevant and have payment integration baked into the Form Builder somehow... but that'll be a project for another day. 

Let me know if you have any trouble with it or spot any other broken links. Thanks!

Ben

**Comment by jlkane** [comment]
Benjamin Keen wrote:
> 
> Hi Jim, all fixed! It's back online here: https://docs.formtools.org/tutorials/paypal/

Thank you SO much for taking the time to get that tutorial back online, Ben.  As I've told you, I'm in awe of your documentation, and this bit will be just the thing to convince my new client that Form Tools is right for her.

With gratitude,

Jim
---
Jim Kane
Simply Effective Web Sites
http://simply-effective.com
(585) 442-7974

**Comment by jlkane** [comment]
Yup, that tutorial did the trick.  We'll have another happy Form Tools user before long!  Thanks again, Ben.

**Comment by benkeen** [comment]
No problem! :)
