### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ProAccess** [formtools/website#17]
Broken links: https://docs.formtools.org/modules/form_builder/customization/anatomy/template_set_anatomy
https://docs.formtools.org/modules/form_builder/customization/anatomy/smarty_lang
https://docs.formtools.org/modules/form_builder/customization/anatomy/customization_tips

**Comment by benkeen** [comment]
Thanks @MacManic! I'll try to fix these up this weekend.

**Comment by benkeen** [comment]
Fixed locally, will be updated on the prod site today.
