### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by deathline** [formtools/website#23]
https://docs.formtools.org/modules/custom_fields/
page "Displaying tabs" url link is not working cause of "T" letter
https://docs.formtools.org/modules/custom_fields/displaying_Tab/
true link is 
https://docs.formtools.org/modules/custom_fields/displaying_tab/

**Comment by benkeen** [comment]
Thanks @deathline!

**Comment by benkeen** [comment]
Docs repo has been updated. I'll update the production documentation later today.

**Comment by paveljee** [comment]
> Docs repo has been updated. I'll update the production documentation later today.

A friendly reminder here the link at [the Custom Fields docs](https://docs.formtools.org/modules/custom_fields/displaying_tab/) still reads `displaying_tcab` instead of `displaying_tab`, so a 404 at https://docs.formtools.org/modules/custom_fields/displaying_tcab/.
