### ISSUE TITLE
broken link of form builder documentation

### ISSUE THREAD

**Issue by tibini** [formtools/website#26]
http://modules.formtools.org/form_builder/ is not  working

**Comment by benkeen** [comment]
Thanks @tibini! Do you recall which page contains the wrong link?

**Comment by tibini** [comment]
Dear Benjamin,

the help page of publishing  form contains this link. See attached...

Thanks,
Tibi

2018-01-14 20:08 GMT+01:00 Benjamin Keen <notifications@github.com>:

**Comment by benkeen** [comment]
Redirects now in place for the modules.
