### ISSUE TITLE
Broken link in System Check documentation

### ISSUE THREAD

**Issue by MikePeters86** [formtools/website#34]
The documentation page on Table Verification [ https://docs.formtools.org/modules/system_check/table_verification/ ] says "Just install the module as usual (see instructions here)" but the link to the instructions [ https://docs.formtools.org/userdoc/installing_modules ] is broken. HTTP 404.

**Comment by benkeen** [comment]
Thanks @MikePeters86! I'll patch that up this weekend.

**Comment by benkeen** [comment]
Fixed here: https://github.com/formtools/docs/commit/45ff8b8f8ea28dafae50047f17a9408493f327d2

I'll update the docs this weekend.
