### ISSUE TITLE
Broken Link - Docs, Module Development

### ISSUE THREAD

**Issue by darusdp** [formtools/website#37]
#1 On this page: https://docs.formtools.org/module_development/ft3/anatomy/ the link for the More Info button associated with the code/Module.class.php section goes to: https://docs.formtools.org/module_development/ft3/file_module

I believe it should be: https://docs.formtools.org/module_development/ft3/module_class/

#2 The link at: https://docs.formtools.org/module_development/ft3/module_nav/ in this sentence 'Your module menu items are defined in your module.php file, as discussed earlier.'  goes to FT2.

I believe it should go to: https://docs.formtools.org/module_development/ft3/module_class/

#3 The link to go to the next page from https://docs.formtools.org/module_development/ft3/display_pages/ is titled Helper Functions. It has this link: https://docs.formtools.org/module_development/ft3/helper_functions/

I believe it should be titled Helper Methods with link: https://docs.formtools.org/module_development/ft3/helper_methods/

**Comment by darusdp** [comment]
#4 On https://docs.formtools.org/module_development/ft3/register_hook/ the link to code hooks in "See the code hooks page" goes to FT2 (https://docs.formtools.org/module_development/code_hooks/),

I believe it should be: https://docs.formtools.org/module_development/ft3/code_hooks/

**Comment by benkeen** [comment]
Thanks, @darusdp - some of the oldest doc on the site, that (but I did update it for FT3). I'll patch this up.

**Comment by benkeen** [comment]
These are all fixed locally; I'll update the prod site later today.
