### ISSUE TITLE
Link broken in tutorial

### ISSUE THREAD

**Issue by jpru** [formtools/website#8]
Hi, 

In Tutorial "Documentation » Tutorials » Adding your first form"
in chapter "Picked your Submission Method?" then link to
"Adding a POST form" is broken.  It leads to
https://docs.formtools.org/tutorials/adding_post_form/
which is not existent.

cu,
Jürgen

**Comment by benkeen** [comment]
Terrific, thanks @jpru! I'll patch that up tonight.

**Comment by benkeen** [comment]
Fixed.
