### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by midodds** [formtools/website#9]
Broken Link in Forms : Views : Filters to "User documentation "

![error](https://cloud.githubusercontent.com/assets/12250317/23836866/f6a0fd0e-0776-11e7-8c2f-caaafc84bd11.png)

**Comment by benkeen** [comment]
Brilliant, thanks @midodds! I'll patch this up tonight.

**Comment by midodds** [comment]
Great tool btw !
Have also found some glitches in filters I will post the details tonite

Sent from my phone, so kept brief

Regards,




Michael Dodds
Program Director

Dell Technologies Select
mobile +44-771-7730378<../../../../Documents/Access%20Applications>
michael.dodds@dell.com<mailto:michael.dodds@dell.com>

Notice of Annual Leave:
<http://www.delltechnologies.com/>
[cid:image001.png@01D20F51.0925DE50]<http://www.delltechnologies.com/>

Business Address: 100 Leadenhall Street<x-apple-data-detectors://3> (3rd Floor), London, Greater London, EC3A 3BP, United Kingdom

Confidentiality Notice: This email message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential or proprietary information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, immediately contact the sender by reply e-mail and destroy all copies of the original message





On 12 Mar 2017, at 23:20, Benjamin Keen <notifications@github.com<mailto:notifications@github.com>> wrote:


Brilliant, thanks @midodds<https://github.com/midodds>! I'll patch this up tonight.

**Comment by benkeen** [comment]
Cool! More bug reports the better! :)

**Comment by benkeen** [comment]
Sorry - didn't get time to add in the redirect tonight, so I may not get to it until Tues night. The correct link should be: https://docs.formtools.org/userdoc/views/standard_filters/

**Comment by midodds** [comment]
Hi Ben

No worries – have been building a simple web application using Formtools and am picking up on bits and pieces. You’ll see I posted some notes about using filters

Let me know if these are useful as I’m happy to share anything else I find


Michael Dodds
Program Director
Dell Technologies Select
mobile +44-771-7730378<../../../../Documents/Access%20Applications>
michael.dodds@dell.com<mailto:michael.dodds@dell.com>

Notice of Annual Leave : 15th March to 21st March inclusive
[cid:image001.png@01D20F51.0925DE50]<http://www.delltechnologies.com/>

Business Address: 100 Leadenhall Street (3rd Floor), London, Greater London, EC3A 3BP, United Kingdom

Confidentiality Notice: This email message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential or proprietary information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, immediately contact the sender by reply e-mail and destroy all copies of the original message

**Comment by benkeen** [comment]
All fixed. Now http://docs.formtools.org/userdoc2_1/index.php?page=view_filters redirects to https://docs.formtools.org/userdoc/views/standard_filters/?page=view_filters. Thanks again!
